import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, {useState, useEffect} from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [message, setMessage] = useState("");
  const [convo, setConvo] = useState([{"message": "I'm your personal vegan coach, how can I help you?", "by": "dan"}]);

  const handleSend = async() => {
    if (!message){
      alert('Enter a message');
      return;
    }
    const firsttemp = [...convo, {"message": message, "by": "user"}];
    setConvo(firsttemp);
    
    const response = await fetch('/api/send', {
      method: 'POST',
      headers: {
        'Content-Type' : 'application/json',
      },
      body: JSON.stringify({
        message,
      }),
    })

    
    
    const data = await response.json();
    console.log(data.data);
    let tempval = data.data.indexOf('{');
    const newdata = data.data.substring(tempval);
    
    
    const jsondata = JSON.parse(newdata);

    const tempconvo = [...convo, {"message": message, "by": "user"},{"message": jsondata.message, "by": "dan"}];
    setConvo(tempconvo);
    setMessage('');
  }
  
  
  return (
    <>
      <Head>
        <title>Vegan Fitness Coach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>  
        <div className='first-banner'>
            <div className='container'>
              <p className='title'>Began Your <span className='green-text'>Vegan</span> Journey.<br/> Talk to Dan.</p>
              <div className='button-container'>
              <a href="#chat"> 
                <button className="first-button  mx-auto lg:mx-0 hover:underline  font-bold rounded-full my-8 py-3 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-125 duration-300 ease-in-out">
                    Chat
                </button>
              </ a>
                
              </div>
            </div>
          </div>
          <div id="chat" className='chat-banner'>
              <div>
              <div class="container mx-auto">
      <div class="max-w-2xl border rounded">
        <div>
          <div class="w-full">
            <div class="relative flex items-center p-3 border-b border-gray-300">
              <img class="object-cover w-10 h-10 rounded-full"
                src="https://cdn.pixabay.com/photo/2018/01/15/07/51/woman-3083383__340.jpg" alt="username" />
              <span class="block ml-2 font-bold text-gray-600">Dan</span>
              <span class="absolute w-3 h-3 bg-green-600 rounded-full left-10 top-3">
              </span>
            </div>
            <div class="relative w-full p-6 overflow-y-auto h-[40rem]">

              <ul class="space-y-2">
                <li class="flex justify-start">
                  <div class="relative max-w-xl px-4 py-2 text-gray-700 rounded shadow">
                    <span class="block">Hi, I'm Dan </span>
                  </div>
                </li>
                {convo.map((con) => (
                  <>
                    
                    <li className={con.by === 'dan'? "flex justify-start" : "flex justify-end"}>
                      <div className={con.by === 'dan'? "relative max-w-xl px-4 py-2 text-gray-700 rounded shadow" : "relative max-w-xl px-4 py-2 text-gray-700 bg-gray-100 rounded shadow"}>
                        <span class="block">{con.message}</span>
                      </div>
                    </li>
                   
                  </>
                ))}
                
              </ul>

            </div>

            <div class="flex items-center justify-between w-full p-3 border-t border-gray-300">

              

              <input type="text" placeholder="Message" onChange={(e) => setMessage(e.target.value)} value={message}
                class="block w-full py-2 pl-4 mx-3 bg-gray-100 rounded-full outline-none focus:text-gray-700"
                name="message" required />
              
              <button type="submit" onClick={handleSend}>
                <svg class="w-5 h-5 text-gray-500 origin-center transform rotate-90" xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 20 20" fill="currentColor">
                  <path
                    d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
              </div>
          </div>
      </main>
    </>
  )
}
